# Generated by Django 2.0.2 on 2018-03-03 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='image')),
                ('url', models.URLField(verbose_name='image url')),
                ('index', models.IntegerField(default=100, verbose_name='image show index')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='image add time')),
            ],
            options={
                'verbose_name': 'idnex page page banner',
                'verbose_name_plural': 'idnex page page banner',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='vertify code')),
                ('email', models.EmailField(max_length=50, verbose_name='email address')),
                ('send_type', models.CharField(choices=[('R', 'register'), ('F', 'forget')], max_length=1, verbose_name='send email type')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='send email time')),
            ],
            options={
                'verbose_name': 'email vetify code',
                'verbose_name_plural': 'email vetify code',
            },
        ),
    ]
