# Generated by Django 2.0.2 on 2018-03-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='F', max_length=1, verbose_name='gender'),
        ),
    ]
