# Generated by Django 2.0 on 2018-03-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnazation', '0003_auto_20180310_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('PXJG', '培训机构'), ('GX', '高校'), ('GR', '个人')], default='PXJG', max_length=4, verbose_name='机构类别'),
        ),
    ]
