# Generated by Django 2.0 on 2018-03-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnazation', '0005_auto_20180315_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='讲师头像'),
        ),
    ]
